# Generated by Django 2.1.7 on 2019-03-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='Email')),
            ],
        ),
    ]
