# Generated by Django 2.1.7 on 2019-03-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('square', models.IntegerField(blank=True, null=True, verbose_name='Площадь')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('rooms', models.IntegerField(blank=True, null=True, verbose_name='Кол-во комнат')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('client_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Стоимость')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Описание')),
            ],
        ),
    ]
